# Q.1) Calculate the total revenue generated by two product categories in a store 

# Input: category1_revenue = np.array([500, 600, 700, 550]) 

# category2_revenue = np.array([450, 700, 800, 600])

# CODE:

# Importing the library
import numpy as np

# Define the revenue array for Category 1 and Category 2
category1_revenue = np.array([500, 600, 700, 550])
category2_revenue = np.array([450, 700, 800, 600])

# Calculate total revenue for each entry
total_revenue = category1_revenue + category2_revenue

#Print the calculated total revenue 
print("Total Revenue generated by two product categories in a store:", total_revenue)

# OUTPUT:
# Total Revenue generated by two product categories in a store: [ 950 1300 1500 1150]
